# this is just a simple test device setup that's used to compile and test the examples

esphome:
    name: birddetectortest
    platform: esp32
    board: esp32cam
    build_path: .build/bird_detector_test